version: '3'

services:
  web:
    build: .
    entrypoint: ["daphne", "-b", "0.0.0.0", "-p", "8000", "chat.asgi:application"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:alpine
